### ISSUE TITLE
broken link in footer

### ISSUE THREAD

**Issue by jameshadfield** [blab/sars-like-cov#1]
The link in the description is to `/sars-like-cov?clade=Wuhan` which (i'm guessing) works locally but doesn't work on nextstrain.org. It should include the groups prefix, like so: `/groups/blab/sars-like-cov?clade=Wuhan`

Additionally, I think the filter names have changed from a previous build so I believe the desired link is `/groups/blab/sars-like-cov?f_virus_type=Wuhan_coronavirus`

**Comment by trvrb** [comment]
Thanks James! I've resolved this.
