### ISSUE TITLE
TreeTime?

### ISSUE THREAD

**Issue by Artoria2e5** [blab/sars-like-cov#2]
The official ncov build for global human samples constructs a [time-resolved tree](https://nextstrain.org/docs/tutorials/zika#get-a-time-resolved-tree). Can we do that here too? (their [snakefile](https://github.com/nextstrain/ncov/blob/master/Snakefile#L162))

**Comment by trvrb** [comment]
TreeTime (and other programs which compute time trees such as BEAST) don't work well for situations where there is substantially evolutionary time. The presence of repeated mutations confused the normal clock estimates. It's possible to infer a date to the common ancestor of nCoV and RaTG13 (see here http://virological.org/t/divergence-of-ncov-2019-to-closest-non-human-relative/388), but I wouldn't go much too much further back than this.
